About Dataset
1. Data Source:
Synthetic data generated and inspired from the paper: Length-weight relationships of nine fish species from the Tetulia River, southern Bangladesh: https://www.researchgate.net/figure/Descriptive-statistics-and-estimated-length-weight-relationship-W-aL-b-W-in-g-and-L_tbl1_280916140

2. Meta Data:
species: species name
length: length (cm)
weight: weight (g)
w_l_ratio: weight / length

3. Usage:
Exploratory Data Analysis (EDA): Understand the distributions, relationships, and patterns within the data.
Classification: Predict the species based on height and length, W/L ratio

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split,GridSearchCV,StratifiedKFold,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [3]:
df=pd.read_csv("fish_data.csv")
df.head()

,species,length,weight,w_l_ratio
0,Anabas testudineus,10.66,3.45,0.32
1,Anabas testudineus,6.91,3.27,0.47
2,Anabas testudineus,8.38,3.46,0.41
3,Anabas testudineus,7.57,3.36,0.44
4,Anabas testudineus,10.83,3.38,0.31


In [4]:
df.species.value_counts()

species
Setipinna taty            480
Anabas testudineus        476
Pethia conchonius         475
Otolithoides biauritus    468
Polynemus paradiseus      458
Sillaginopsis panijus     455
Otolithoides pama         435
Puntius lateristriga      418
Coilia dussumieri         415
Name: count, dtype: int64

In [ ]:
 #dividing the data into features and target
X=df.drop("species",axis=1)
y=df["species"]   
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [6]:
# defining the model with multi_class as ovr
logistic=LogisticRegression(multi_class="ovr")
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

c:\Users\123456\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [7]:
print(classification_report(y_test,y_pred))

                        precision    recall  f1-score   support

    Anabas testudineus       1.00      0.96      0.98       160
     Coilia dussumieri       1.00      1.00      1.00       125
Otolithoides biauritus       0.81      0.27      0.40       141
     Otolithoides pama       1.00      0.95      0.98       129
     Pethia conchonius       0.96      1.00      0.98       132
  Polynemus paradiseus       0.96      0.97      0.96       159
  Puntius lateristriga       1.00      1.00      1.00       105
        Setipinna taty       0.58      0.98      0.73       146
 Sillaginopsis panijus       1.00      1.00      1.00       127

              accuracy                           0.90      1224
             macro avg       0.92      0.90      0.89      1224
          weighted avg       0.92      0.90      0.89      1224



In [8]:
print(accuracy_score(y_test,y_pred))

0.8986928104575164


In [9]:
print(confusion_matrix(y_test,y_pred))

[[153   0   0   0   0   7   0   0   0]
 [  0 125   0   0   0   0   0   0   0]
 [  0   0  38   0   0   0   0 103   0]
 [  0   0   6 123   0   0   0   0   0]
 [  0   0   0   0 132   0   0   0   0]
 [  0   0   0   0   5 154   0   0   0]
 [  0   0   0   0   0   0 105   0   0]
 [  0   0   3   0   0   0   0 143   0]
 [  0   0   0   0   0   0   0   0 127]]
